### ISSUE TITLE
Touchscreen unresponsive after sleep.

### ISSUE THREAD

**Issue by bedawi** [bedawi/trekstor-s11b#1]
The Goodix touchscreen of the Trekstor Primetab S11B stops working after suspend. Unloading and loading the kernel module (goodix, insmod /lib/modules/5.3.15-300.fc31.x86_64/kernel/drivers/input/touchscreen/goodix.ko.xz) produces and error, but only after suspend.

Output of journal BEFORE SUSPEND when running ``rmmod goodix && modprobe -v goodix``:

kernel: Goodix-TS i2c-GDIX1001:00: i2c-GDIX1001:00 supply AVDD28 not found, using dummy regulator
kernel: Goodix-TS i2c-GDIX1001:00: i2c-GDIX1001:00 supply VDDIO not found, using dummy regulator
kernel: Goodix-TS i2c-GDIX1001:00: ID 928, version: 1040
kernel: input: Goodix Capacitive TouchScreen as /devices/pci0000:00/0000:00:16.3/i2c_designware.3/i2c-8/i2c-GDIX1001:00/input/input20

Output of journal AFTER SUSPEND when running rmmod goodix && modprobe -v goodix:

kernel: Goodix-TS i2c-GDIX1001:00: i2c-GDIX1001:00 supply AVDD28 not found, using dummy regulator
kernel: Goodix-TS i2c-GDIX1001:00: i2c-GDIX1001:00 supply VDDIO not found, using dummy regulator
kernel: Goodix-TS i2c-GDIX1001:00: ID 928, version: 1040
kernel: Goodix-TS i2c-GDIX1001:00: Invalid config (0, 0, 0), using defaults
kernel: input: Goodix Capacitive TouchScreen as /devices/pci0000:00/0000:00:16.3/i2c_designware.3/i2c-8/i2c-GDIX1001:00/input/input21

**Comment by bedawi** [comment]
Bugreport filed; [Redhat Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1786317)

**Comment by bedawi** [comment]
Temporary kernel build with patches available:

To install it, please run these commands:
```
mkdir rpms
cd rpms
wget https://kojipkgs.fedoraproject.org//work/tasks/4675/39964675/kernel-core-5.4.6-200.rhbz1786317.fc31.x86_64.rpm
wget https://kojipkgs.fedoraproject.org//work/tasks/4675/39964675/kernel-modules-5.4.6-200.rhbz1786317.fc31.x86_64.rpm
sudo rpm -ivh --oldpackage kernel-*.rpm
```

Also the keyboard cover now works properly with this kernel, so the kernel arguments you probably added from my workaround hack can be removed from grubby:
`sudo grubby --update-kernel=ALL --remove-args="rd.driver.blacklist=hid_multitouch" --make-default`

Reboot to use the new kernel. Remember that updating your Fedora Linux might install a newer Kernel which has not yet been patched. So, until an official Kernel with patches for this Bug has been published, do not update your kernel.

Reboot:
`sudo reboot`

**Comment by ruathudo** [comment]
Hi, I have the same issue with goodix touchscreen driver on Fedora 31 kernel 5.4.10 stable.
As I see the path is available for kernel-core-5.4.6-200.rhbz1786317.fc31, I'm noob so my question is that shouldn't it be patched for newer stable version?
If not, do you know when this patch is available for fedora stable kernel ? thanks.

**Comment by bedawi** [comment]
Hi ruathudo,

a patch will be part of official kernels in the future. The Ticket on [bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1786317) is not yet closed. 

:-)

Many greetings
Ben

**Comment by ruathudo** [comment]
Great! many thanks for your excellent work.

**Comment by bedawi** [comment]
Problem solved. A kernel module can now be installed on Fedora 31 to fix the issue. 
[https://github.com/bedawi/trekstor-s11b/tree/master/kernel-mod](https://github.com/bedawi/trekstor-s11b/tree/master/kernel-mod)

Many thanks to [Hans de Goede](https://github.com/jwrdegoede) for fixing this bug!
